// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxQc4xCvZS5Nk-ibDeHhA39Xhqmk0-B0',
    appId: '1:51231961760:web:1471d1cffc7368570f8fc5',
    messagingSenderId: '51231961760',
    projectId: 'todofirebase-b1e77',
    authDomain: 'todofirebase-b1e77.firebaseapp.com',
    storageBucket: 'todofirebase-b1e77.appspot.com',
    measurementId: 'G-WY4YHV7VPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIT5FCHoWW4BQ83rvwsG_qongUKSzY1eE',
    appId: '1:51231961760:android:26fcf4615bbb8efc0f8fc5',
    messagingSenderId: '51231961760',
    projectId: 'todofirebase-b1e77',
    storageBucket: 'todofirebase-b1e77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6jxaKe0iwWhTTPMYNsIlmJiof1fnHcE',
    appId: '1:51231961760:ios:fa36a6aae99c85ba0f8fc5',
    messagingSenderId: '51231961760',
    projectId: 'todofirebase-b1e77',
    storageBucket: 'todofirebase-b1e77.appspot.com',
    iosClientId: '51231961760-3h6s5o2sc438pqss68rjqpek0999ulga.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ6jxaKe0iwWhTTPMYNsIlmJiof1fnHcE',
    appId: '1:51231961760:ios:fa36a6aae99c85ba0f8fc5',
    messagingSenderId: '51231961760',
    projectId: 'todofirebase-b1e77',
    storageBucket: 'todofirebase-b1e77.appspot.com',
    iosClientId: '51231961760-3h6s5o2sc438pqss68rjqpek0999ulga.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
